language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
 - pip install -r requirements.txt
 - pip install coverage pytest-runner
 - python setup.py install
# command to run tests
script: py.test
script:
  coverage run --source=pyosf setup.py test
after_success:
  coveralls